#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Murtain.App.Bindings.Droid.PickerView.Demo.Resource", IsApplication=true)]

namespace Murtain.App.Bindings.Droid.PickerView.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int pickerview_dividerColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int pickerview_gravity = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int pickerview_textColorCenter = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int pickerview_textColorOut = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int pickerview_textSize = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int pickerview_customTextSize = 2131034112;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int bgColor_overlay = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int pickerview_bg_topbar = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int pickerview_timebtn_nor = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int pickerview_timebtn_pre = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int pickerview_topbar_title = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int pickerview_wheelview_textcolor_center = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int pickerview_wheelview_textcolor_divider = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int pickerview_wheelview_textcolor_out = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int pickerview_textsize = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int pickerview_topbar_btn_textsize = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int pickerview_topbar_height = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int pickerview_topbar_paddingleft = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int pickerview_topbar_paddingright = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int pickerview_topbar_title_textsize = 2131165189;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int selector_pickerview_btn = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0008
			public const int MyButton = 2131361800;
			
			// aapt resource value: 0x7f0a0003
			public const int btnCancel = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int btnCascadingSelection = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int btnDatePicker = 2131361801;
			
			// aapt resource value: 0x7f0a0005
			public const int btnSubmit = 2131361797;
			
			// aapt resource value: 0x7f0a0000
			public const int center = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int content_container = 2131361799;
			
			// aapt resource value: 0x7f0a0012
			public const int day = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int hour = 2131361811;
			
			// aapt resource value: 0x7f0a0001
			public const int left = 2131361793;
			
			// aapt resource value: 0x7f0a0014
			public const int min = 2131361812;
			
			// aapt resource value: 0x7f0a0011
			public const int month = 2131361809;
			
			// aapt resource value: 0x7f0a000c
			public const int options1 = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int options2 = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int options3 = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int optionspicker = 2131361803;
			
			// aapt resource value: 0x7f0a0006
			public const int outmost_container = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int right = 2131361794;
			
			// aapt resource value: 0x7f0a000f
			public const int timepicker = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int tvTitle = 2131361796;
			
			// aapt resource value: 0x7f0a0010
			public const int year = 2131361808;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int animation_default_duration = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Bools = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dimens = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int include_pickerview_topbar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout_basepickerview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int pickerview_options = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int pickerview_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090009
			public const int ApplicationName = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int Hello = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int pickerview_cancel = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int pickerview_day = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int pickerview_hours = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int pickerview_minutes = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int pickerview_month = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int pickerview_seconds = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int pickerview_submit = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int pickerview_year = 2131296263;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] pickerview = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 4
			public const int pickerview_pickerview_dividerColor = 4;
			
			// aapt resource value: 0
			public const int pickerview_pickerview_gravity = 0;
			
			// aapt resource value: 3
			public const int pickerview_pickerview_textColorCenter = 3;
			
			// aapt resource value: 2
			public const int pickerview_pickerview_textColorOut = 2;
			
			// aapt resource value: 1
			public const int pickerview_pickerview_textSize = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
