#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Murtain.App.Droid.BlurView.Demo.Resource", IsApplication=true)]

namespace Murtain.App.Droid.BlurView.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Murtain.App.Droid.BlurView.Resource.Attribute.disabled = global::Murtain.App.Droid.BlurView.Demo.Resource.Attribute.disabled;
			global::Murtain.App.Droid.BlurView.Resource.Attribute.move = global::Murtain.App.Droid.BlurView.Demo.Resource.Attribute.move;
			global::Murtain.App.Droid.BlurView.Resource.Attribute.src = global::Murtain.App.Droid.BlurView.Demo.Resource.Attribute.src;
			global::Murtain.App.Droid.BlurView.Resource.Id.BlurViewBlurImageView = global::Murtain.App.Droid.BlurView.Demo.Resource.Id.BlurViewBlurImageView;
			global::Murtain.App.Droid.BlurView.Resource.Id.BlurViewOriginImageView = global::Murtain.App.Droid.BlurView.Demo.Resource.Id.BlurViewOriginImageView;
			global::Murtain.App.Droid.BlurView.Resource.Layout.BlurView = global::Murtain.App.Droid.BlurView.Demo.Resource.Layout.BlurView;
			global::Murtain.App.Droid.BlurView.Resource.String.ApplicationName = global::Murtain.App.Droid.BlurView.Demo.Resource.String.ApplicationName;
			global::Murtain.App.Droid.BlurView.Resource.String.Hello = global::Murtain.App.Droid.BlurView.Demo.Resource.String.Hello;
			global::Murtain.App.Droid.BlurView.Resource.Styleable.blur_layout = global::Murtain.App.Droid.BlurView.Demo.Resource.Styleable.blur_layout;
			global::Murtain.App.Droid.BlurView.Resource.Styleable.blur_layout_disabled = global::Murtain.App.Droid.BlurView.Demo.Resource.Styleable.blur_layout_disabled;
			global::Murtain.App.Droid.BlurView.Resource.Styleable.blur_layout_move = global::Murtain.App.Droid.BlurView.Demo.Resource.Styleable.blur_layout_move;
			global::Murtain.App.Droid.BlurView.Resource.Styleable.blur_layout_src = global::Murtain.App.Droid.BlurView.Demo.Resource.Styleable.blur_layout_src;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int disabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int move = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int src = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dayu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int BlurViewBlurImageView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int BlurViewOriginImageView = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int MainBlurView = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MainLinearLayout = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int MainSeekBar = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlurView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] blur_layout = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int blur_layout_disabled = 2;
			
			// aapt resource value: 1
			public const int blur_layout_move = 1;
			
			// aapt resource value: 0
			public const int blur_layout_src = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
