#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Murtain.App.Bindings.Droid.SVProgressHUD.Demo.Resource", IsApplication=true)]

namespace Murtain.App.Bindings.Droid.SVProgressHUD.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int svfade_in_center = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int svfade_out_center = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int svslide_in_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int svslide_in_top = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int svslide_out_bottom = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int svslide_out_top = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int svprogress_max = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int svprogress_roundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int svprogress_roundProgressColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int svprogress_roundWidth = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int svprogress_style = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int bgColor_overlay = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bgColor_overlay_black = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int bgColor_svprogressdefaultview = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int roundColor_svprogresshuddefault = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int roundProgressColor_svprogresshuddefault = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textColor_svprogresshuddefault_msg = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int margintop_svprogresshuddefault_msg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int padding_svprogresshuddefault = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int radius_svprogresshuddefault = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int size_image_bigloading = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int size_image_smallloading = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int size_minwidth_svprogresshuddefault = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textSize_svprogresshuddefault_msg = 2131099654;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_overlay_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_svprogresshuddefault = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_svstatus_error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_svstatus_info = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_svstatus_loading = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_svstatus_success = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int FILL = 2131361792;
			
			// aapt resource value: 0x7f0a0003
			public const int MyButton = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int STROKE = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int circleProgressBar = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int ivBigLoading = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int ivSmallLoading = 2131361797;
			
			// aapt resource value: 0x7f0a0002
			public const int sv_outmost_container = 2131361794;
			
			// aapt resource value: 0x7f0a0007
			public const int tvMsg = 2131361799;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int svanimation_default_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_svprogresshud = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int view_svprogressdefault = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AlertActivity_AlertStyle = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SVCircleProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 3
			public const int SVCircleProgressBar_svprogress_max = 3;
			
			// aapt resource value: 0
			public const int SVCircleProgressBar_svprogress_roundColor = 0;
			
			// aapt resource value: 1
			public const int SVCircleProgressBar_svprogress_roundProgressColor = 1;
			
			// aapt resource value: 2
			public const int SVCircleProgressBar_svprogress_roundWidth = 2;
			
			// aapt resource value: 4
			public const int SVCircleProgressBar_svprogress_style = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
